name: PHP Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.4', '8.3', '8.2', '8.1', '8.0']

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, json, xdebug, curl
        coverage: pcov
        tools: composer:v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Adjust composer dependencies for older PHP versions
      if: contains(matrix.php-version, '8.0, 8.1')
      run: |
        php php-version-deps-adjust.php
        composer update --no-progress --no-interaction

    - name: Install dependencies
      run: composer install --no-progress --no-interaction

    - name: Run test suites for older PHP versions
      if: contains(matrix.php-version, '8.0, 8.1, 8.2, 8.3')
      run: composer run-script test-all

    - name: Run test suites with coverage for latest PHP version
      if: matrix.php-version == '8.4'
      run: |
        mkdir -p var/coverage
        php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-text --coverage-clover=var/coverage/clover.xml | tee var/coverage/coverage.txt

    - name: Extract Line Coverage
      if: matrix.php-version == '8.4'
      id: coverage
      run: echo "COVERAGE=$(grep -oP '(?<=Lines:\s+)[\d\.]+' coverage.txt | tail -1)" >> $GITHUB_ENV

    - name: Update GitHub Status
      if: matrix.php-version == '8.4'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -d "{\"state\":\"success\",\"context\":\"Code Coverage\",\"description\":\"Line Coverage: ${{ env.COVERAGE }}%\",\"target_url\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
