name: PHPStan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

env:
  PHP_VERSION: '8.3'

jobs:
  cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, json
          tools: composer:v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.3-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PHP_VERSION }}-

      - name: Run PHP CS Fixer
        run: |
          vendor/bin/phpstan
