name: PR Coverage

on:
  pull_request:
    branches: [ "**" ]

jobs:
  check-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Indicate pending code coverage check
      id: coverage-indicate
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
          -d '{
            "state": "pending",
            "context": "Code Coverage",
            "description": "Coverage: ?%",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, json, xdebug, curl
        coverage: pcov
        tools: composer:v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ php-version }}-

    - name: Run test suites with coverage
      run: |
        mkdir -p var/coverage
        php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-text --coverage-clover=var/coverage/clover.xml

    - name: Extract Coverage
      if: success()
      id: coverage-gather
      run: |
        COVERAGE=$(php scripts/get-coverage.php var/coverage/clover.xml)
        STATUS=$(if [ "$COVERAGE" -ge "95" ]; then echo "success"; else echo "failure"; fi)
        echo "COVERAGE_PERCENT=${COVERAGE}" >> $GITHUB_ENV
        echo "COVERAGE_STATUS=${STATUS}" >> $GITHUB_ENV

    - name: Update GitHub status with code coverage
      if: success()
      id: coverage-send
      run: |        
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
          -d '{
            "state": "success",
            "context": "Code Coverage",
            "description": "Coverage: ${{ env.COVERAGE_PERCENT }}%",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
